### ISSUE TITLE
Don't send emails to disabled users

### ISSUE THREAD

**Issue by swissspidy** [jaredatch/Disable-Users#5]
A small feature request that might be a good fit for this plugin.

On a corporate blog I help maintain there are some authors who are no longer part of the team. Of course their posts should stay, so they aren't deleted. The problem they still get the email notifications for new comments on their posts.

I thought disabling users could also mean don't send any emails to these users. Or at least no comment notification users.

**Comment by jaredatch** [comment]
Makes sense to me and I like the logic. In my own use cases where users are disabled, I agree, I don't want them to get any emails.

Something I'll look into when I get time.

**Comment by JosefJezek** [comment]
:+1:

**Comment by JustThomas** [comment]
That sounds like an interesting feature. I'll look into this and maybe send you a pull request.
