### ISSUE TITLE
Support for Roles

### ISSUE THREAD

**Issue by TehEnforce** [jaredatch/Disable-Users#6]
Please add support for roles/permissions so my staff can block users aswell.

The roles/permissions plugin I use: "WPFront User Role Editor"

**Comment by jaredatch** [comment]
You will need to give me more specific details because I'm not sure I follow. 

What is the use case?

I think maybe you are talking about capabilities instead? (eg making the cap check filterable https://github.com/jaredatch/Disable-Users/blob/master/init.php#L101)

**Comment by TehEnforce** [comment]
Yes that was it. Thanks.
